apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: jitsi
  template:
    metadata:
      labels:
        component: jitsi
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                - matchExpressions:
                    - key: audio
                      operator: In
                      values:
                        - enabled
              weight: 100
      containers:
        - name: web
          image: jitsi/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            ### OPTIONAL: Un-comment the next 2 lines to use Etherpad integration (for document sharing) and apply 'jitsi-meet-etherpad.yaml'
            # - name: ETHERPAD_URL_BASE
            #   value: http://etherpad:9001
          {{- include "jitsi-meet.common.env" . | nindent 12 }}
          volumeMounts:
            - name: jitsi-config
              mountPath: /config
            {{- if .Values.jitsi.config.enabled }}
            - name: jitsi-interface-config
              subPath: interface_config
              mountPath: /config/interface_config.js
            {{- end }}
            # - name: letsencrypt-config
            #  mountPath: /etc/letsencrypt
            - name: jitsi-transcripts
              mountPath: /usr/share/jitsi-meet/transcripts
      volumes:
        - name: jitsi-config
          emptyDir: {}
        ### OPTIONAL: Un-comment the next 3 lines to use the configMap
        {{- if .Values.jitsi.config.enabled }}
        - name: jitsi-interface-config
          configMap:
            name: jitsi-interface-config
        {{- end }}
        #- name: letsencrypt-config
        #   emptyDir: {}
        - name: jitsi-transcripts
          emptyDir: {}
