### Video bridge
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: jvb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: jvb
  template:
    metadata:
      labels:
        component: jvb
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: audio
                    operator: In
                    values:
                      - enabled
              weight: 1
      containers:
        - name: jvb
          image: jitsi/jvb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4443
              protocol: TCP
            - name: proxy-udp-10000
              containerPort: 10000
              hostPort: 10000
              protocol: UDP
          env:
            {{- include "jitsi-meet.common.env" . | nindent 12 }}
          volumeMounts:
            - name: jvb-config
              mountPath: /config
      volumes:
        - name: jvb-config
          emptyDir: {}
