apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: jitsi
  template:
    metadata:
      labels:
        component: jitsi
    spec:
      containers:
        - name: web
          image: jitsi/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            - name: PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: PUBLIC_URL
            - name: TZ
              value: {{ .Values.jitsi.common.timezone }}
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "false"
            - name: JIBRI_XMPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JIBRI_XMPP_PASSWORD
            - name: JIBRI_RECORDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JIBRI_RECORDER_PASSWORD
            ### OPTIONAL: Un-comment the next 2 lines to use Etherpad integration (for document sharing) and apply 'jitsi-meet-etherpad.yaml'
            # - name: ETHERPAD_URL_BASE
            #   value: http://etherpad:9001
          volumeMounts:
            - name: jitsi-config
              mountPath: /config
            {{- if .Values.jitsi.config.enabled }}
            - name: jitsi-interface-config
              subPath: interface_config
              mountPath: /config/interface_config.js
            {{- end }}
            # - name: letsencrypt-config
            #  mountPath: /etc/letsencrypt
            - name: jitsi-transcripts
              mountPath: /usr/share/jitsi-meet/transcripts
      volumes:
        - name: jitsi-config
          emptyDir: {}
        {{- if .Values.jitsi.config.enabled }}
        - name: jitsi-interface-config
          configMap:
            name: jitsi-interface-config
        {{- end }}
        #- name: letsencrypt-config
        #   emptyDir: {}
        - name: jitsi-transcripts
          emptyDir: {}
