apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: jicofo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: jicofo
  template:
    metadata:
      labels:
        component: jicofo
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                - matchExpressions:
                    - key: audio
                      operator: In
                      values:
                        - enabled
              weight: 100
      containers:
        - name: jicofo
          image: jitsi/jicofo:latest
          imagePullPolicy: Always
          env:
            {{- include "jitsi-meet.common.env" . | nindent 12 }}
          volumeMounts:
            - name: jicofo-config
              mountPath: /config
      volumes:
        - name: jicofo-config
          emptyDir: {}
