### XMPP server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: prosody
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: prosody
  template:
    metadata:
      labels:
        component: prosody
    spec:
      containers:
        - name: prosody
          image: jitsi/jibri:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5222
              protocol: TCP
            - containerPort: 5269
              protocol: TCP
            - containerPort: 5280
              protocol: TCP
            - containerPort: 5347
              protocol: TCP
          env:
            - name: DISPLAY
              value: ":0"
            - name: JIBRI_PENDING_TIMEOUT
              value: "90"
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: {{ .Values.jitsi.common.timezone }}
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "false"
          volumeMounts:
            - name: jibri-config
              mountPath: /config
            - name: jibri-custom-plugins
              mountPath: /jibri-plugins-custom
      volumes:
        - name: jibri-config
          emptyDir: {}
        - name: jibri-custom-plugins
          emptyDir: {}
