### Video bridge
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: jvb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: jvb
  template:
    metadata:
      labels:
        component: jvb
    spec:
      containers:
        - name: jvb
          image: jitsi/jvb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4443
              protocol: TCP
            - name: proxy-udp-10000
              containerPort: 10000
              hostPort: 10000
              protocol: UDP
          env:
            - name: DOCKER_HOST_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: DOCKER_HOST_ADDRESS
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
          volumeMounts:
            - name: jvb-config
              mountPath: /config
      volumes:
        - name: jvb-config
          emptyDir: {}
