### XMPP server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jibri
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: jibri
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: jibri
  template:
    metadata:
      labels:
        component: jibri
    spec:
      containers:
        - name: jibri
          image: jitsi/jibri:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5222
              protocol: TCP
            - containerPort: 5269
              protocol: TCP
            - containerPort: 5280
              protocol: TCP
            - containerPort: 5347
              protocol: TCP
          env:
            - name: DISPLAY
              value: ":0"
            - name: JIBRI_PENDING_TIMEOUT
              value: "90"
            - name: JIBRI_RECORDER_USER
              value: recorder
            - name: JIBRI_RECORDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JIBRI_RECORDER_PASSWORD
            - name: JIBRI_XMPP_USER
              value: jibri
            - name: JIBRI_XMPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JIBRI_XMPP_PASSWORD
            {{- include "jitsi-meet.common.env" . | nindent 12 }}
          volumeMounts:
            - name: jibri-config
              mountPath: /config
            - name: jibri-custom-plugins
              mountPath: /jibri-plugins-custom
            - name: dev-snd
              mountPath: /dev/snd
      volumes:
        - name: jibri-config
          emptyDir: {}
        - name: jibri-custom-plugins
          emptyDir: {}
        - name: dev-snd
          hostPath:
            path: /dev/snd
