{{- if .Values.jitsi.ingress.enabled -}}
{{- $fullName := include "jitsi-meet.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "jitsi-meet.labels" . | nindent 4 }}
  {{- with .Values.jitsi.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.jitsi.ingress.tls }}
  tls:
    {{- range .Values.jitsi.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.jitsi.ingress.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: web
                port:
                  name: "http"
  {{- end }}
