apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: {{ randAlphaNum 16 | b64enc }}
  JICOFO_AUTH_PASSWORD: {{ randAlphaNum 16 | b64enc}}
  JVB_AUTH_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  JIGASI_XMPP_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  JIBRI_RECORDER_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  JIBRI_XMPP_PASSWORD: {{ randAlphaNum 16 | b64enc}}
  DOCKER_HOST_ADDRESS: {{ "localhost" | b64enc }}
  PUBLIC_URL: {{ .Values.jitsi.common.public_url | b64enc }}
