apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
data:
  DOCKER_HOST_ADDRESS: localhost
  JIBRI_RECORDER_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  JIBRI_XMPP_PASSWORD: {{ randAlphaNum 16 | b64enc}}
  JICOFO_AUTH_PASSWORD: {{ randAlphaNum 16 | b64enc}}
  JICOFO_COMPONENT_SECRET: {{ randAlphaNum 16 | b64enc }}
  JIGASI_XMPP_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  JVB_AUTH_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  PUBLIC_URL: {{ .Values.jitsi.common.public_url }}