apiVersion: v1
kind: Service
metadata:
  name: prosody
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
    app: jitsi-meet
    component: prosody-service
spec:
  ports:
    - name: 5222-tcp
      port: 5222
      targetPort: 5222
    - name: 5280-tcp
      port: 5280
      targetPort: 5280
    - name: 5347-tcp
      port: 5347
      targetPort: 5347
  selector:
    component: prosody